name: 'Next Release Version'
description: 'Find the right semantic version for the next release'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  repo:
    description: 'The repository name'
    default: ${{ github.repository }}
    required: false
  username:
    description: 'GitHub username'
    default: ${{ github.repository_owner }}
    required: false
  token:
    description: 'GitHub token'
    required: true
  branch:
    description: 'The current branch'
    default: ${{ github.ref }}
    required: false
  project:
    description: 'The Project Type (Single or Multi)'
    required: false
    default: 'Single'
outputs:
  next-version:
    description: 'The next semantic version for the next release'
  folder:
    description: 'The name of the folder for the branch'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --repo
    - ${{ inputs.repo }}
    - --username
    - ${{ inputs.username }}
    - --token
    - ${{ inputs.token }}
    - --branch
    - ${{ inputs.branch }}
    - --project
    - ${{ inputs.project }}
