name: 'Next Release Version'
description: 'Find the right semantic version for the next release'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  owner:
    description: 'Owner of the repository'
    required: true
  repo:
    description: 'The repository name'
    required: true
  username:
    description: 'GitHub username'
    required: true
  token:
    description: 'GitHub token'
    required: true
  branch:
    description: 'The current branch'
    required: true
  project:
    description: 'The Project Type (Single or Multi)'
    required: false
    default: 'Single'
outputs:
  next-version:
    description: 'The next semantic version for the next release'
  folder:
    description: 'The name of the folder for the branch'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--owner ${{ inputs.owner }}'
    - '--repo ${{ inputs.repo }}'
    - '--token ${{ inputs.token }}'
    - '--branch ${{ inputs.branch }}'
    - '--project ${{ inputs.project }}'
